# Generated by Django 2.1.1 on 2019-01-17 09:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190117_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 17, 9, 9, 34, 462289, tzinfo=utc)),
        ),
    ]
