# Generated by Django 2.1.1 on 2019-01-17 09:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190117_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 17, 9, 42, 55, 532134, tzinfo=utc)),
        ),
    ]
